remote_theme    : Drassil/git-wiki-theme@master
plugins         :
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
  - jekyll-gitlab-metadata

title                   : dms wiki
description             : 
lang                    : en
encoding                : utf-8
port                    : 443
git_branch              : "main"
baseurl                 : "/wiki"

search_engine           : "js"
disable_edit            : false
show_wiki_pages         : true
show_wiki_pages_limit   : 10
blog_feature            : true
show_wiki_posts         : true
show_wiki_posts_limit   : 10
paginate                : 5
paginate_path           : "/page/:num"
permalink               : "/post/:title"
show_downloads          : false


defaults:
 -
    scope:
      path: ""
    values:
      layout: "git-wiki-bs-lux"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "git-wiki-bs-lux"
